spring.application.name=SpringBootBedrock

server.port=8080

spring.ai.bedrock.aws.region=us-east-1

spring.ai.bedrock.aws.access-key=AKIA44DBIEJ7FORD2ZN6

spring.ai.bedrock.aws.secret-key=your_secret_key

spring.ai.bedrock.converse.chat.options.model=amazon.nova-lite-v1:0